import {
  Instagram,
  Store,
  NotebookText,
  SquarePlus,
  Shirt,
  TextCursorInput,
  TextCursor,
  PhoneIncoming,
  List,
  SlidersHorizontal,
  ListFilter,
  SquareCheck,
  Component,
  ToggleRight,
  Link2,
  Mail,
  KeyRound,
  CalendarRange,
  CalendarClock,
  CalendarFold,
  Calendar,
  CalendarSearch,
  Palette,
  MessageSquare,
  MessageSquareText,
  MessageCircleMore,
  Star,
  Smile,
  ArrowUpDown,
  ImageUp,
  Images,
  ClipboardPen,
  Rows2,
  Linkedin,
  Twitter,
  MessageCircle,
  Hash,
  AlignLeft,
  BarChart2,
  User,
  Users,
  ChevronDown,
  Square,
  Image,
  BadgeCheck,
  MousePointer,
  Layout,
  Grid,
  ListIcon,
  AlignJustify,
  Columns,
  Scroll,
  ChevronRight,
  Table,
  BarChart,
  FileText,
  Monitor,
  Menu,
  PictureInPicture2,
  PanelLeft,
  Columns2,
  Text,
  LaptopMinimal,
  LayoutTemplate,
  Braces,
  TrendingUpDown,
  Trash2,
  Vote,
  CircleCheck,
  ChartNoAxesGantt,
  Phone,
  CalendarDays,
  LetterText,
  Columns3,
  Rows3,
  Clock2,
  AppWindowMac,
  Smartphone,
  Plus,
  Upload,
  Database,
  Parentheses,
  Workflow,
  Pipette,
  Network,
  CircleDot,
  DiamondPlus,
  CirclePlay,
} from "lucide-react";

export default function DynamicIcon({ name, size, style = {}}) {
  const icon_map = {
    instagram: <Instagram size={size} style={{...style}}/>,
    store: <Store size={size} style={{...style}}/>,
    "plus": <Plus size={size} style={{...style}}/>,
    "notebook-text": <NotebookText size={size} style={{...style}}/>,
    "square-plus": <SquarePlus size={size} style={{...style}}/>,
    shirt: <Shirt size={size} style={{...style}}/>,
    "text-cursor-input": <TextCursorInput size={size} style={{...style}}/>,
    "text-cursor": <TextCursor size={size} style={{...style}}/>,
    "phone-incoming": <PhoneIncoming size={size} style={{...style}}/>,
    list: <List size={size} style={{...style}}/>,
    "sliders-horizontal": <SlidersHorizontal size={size} style={{...style}}/>,
    "list-filter": <ListFilter size={size} />,
    "square-check": <SquareCheck size={size} />,
    component: <Component size={size} />,
    "toggle-right": <ToggleRight size={size} />,
    "link-2": <Link2 size={size} />,
    mail: <Mail size={size} />,
    "key-round": <KeyRound size={size} />,
    "calendar-range": <CalendarRange size={size} />,
    "calendar-clock": <CalendarClock size={size} />,
    "calendar-fold": <CalendarFold size={size} />,
    calendar: <Calendar size={size} />,
    "calendar-search": <CalendarSearch size={size} />,
    palette: <Palette size={size} />,
    "message-square": <MessageSquare size={size} />,
    "message-square-text": <MessageSquareText size={size} />,
    "message-circle-more": <MessageCircleMore size={size} />,
    star: <Star size={size} />,
    smile: <Smile size={size} />,
    "arrow-up-down": <ArrowUpDown size={size} />,
    "image-up": <ImageUp size={size} />,
    images: <Images size={size} />,
    "clipboard-pen": <ClipboardPen size={size} />,
    "rows-2": <Rows2 size={size} />,
    linkedin: <Linkedin size={size} />,
    twitter: <Twitter size={size} />,
    whatsapp: <MessageCircle size={size} />,
    "hash": <Hash size={size}/>,
    "align-left": <AlignLeft size={size}/>,
    "bar-chart-2": <BarChart2 size={size}/>,
    "user": <User size={size}/>,
    "users": <Users size={size}/>,
    "chevron-down": <ChevronDown size={size}/>,
    "square":<Square size={size}/>,
    "image": <Image size={size}/>,
    "badge-check": <BadgeCheck size={size}/>,
    "mouse-pointer":<MousePointer size={size}/>,
    "layout": <Layout size={size}/>,
    "grid": <Grid size={size}/>,
    "align-justify": <AlignJustify size={size}/>,
    "columns": <Columns size={size}/>,
    "scroll": <Scroll size={size}/>,
    "chevrons-right": <ChevronRight size={size}/>,
    "table": <Table size={size}/>,
    "bar-chart": <BarChart size={size}/>,
    "file-text": <FileText size={size}/>,
    "monitor": <Monitor size={size}/>,
    "menu": <Menu size={size} />,
    "picture-in-picture-2": <PictureInPicture2 size={size}/>,
    "panel-left": <PanelLeft size={size}/>,
    "columns-2": <Columns2 size={size}/>,
    "text": <Text size={size}/>,
    "laptop-minimal": <LaptopMinimal size={size}/>,
    "layout-template": <LayoutTemplate size={size}/>,
    "trending-up-down": <TrendingUpDown size={size}/>,
    "braces": <Braces size={size}/>,
    "delete":<Trash2 size={size} />,
    "vote": <Vote size={size}/>,
    "circle-check": <CircleCheck size={size} style={{...style}}/>,
    "list-filter-plus": <ListFilter size={size} style={{...style}}/>,
    "chart-no-axes-gant": <ChartNoAxesGantt size={size} style={{...style}}/>,
    "sliders-horizantal": <SlidersHorizontal size={size} style={{...style}}/>,
    "phone": <Phone size={size} style={{...style}}/>,
    "calendar-days": <CalendarDays size={size} style={{...style}}/>,
    "letter-text": <LetterText size={size} style={{...style}}/>,
    "columns-3": <Columns3 size={size} style={{...style}}/>,
    "rows-3": <Rows3 size={size} style={{...style}}/>,
    "clock-2": <Clock2 size={size} style={{...style}}/>,
    "app-window-mac": <AppWindowMac size={size} style={{...style}}/>,
    "smartphone":<Smartphone size={size} style={{...style}}/>,
    "upload": <Upload size={size} style={{...style}}/>,
    "database": <Database size={size} style={{...style}}/>,
    "parentheses": <Parentheses size={size} style={{...style}}/>,
    "workflow": <Workflow size={size} style={{...style}}/>,
    "pipette": <Pipette size={size} style={{...style}}/>,
    "network": <Network size={size} style={{...style}}/>,
    "circle-dot": <CircleDot size={size} style={{...style}}/>,
    "diamond-plus": <DiamondPlus size={size} style={{...style}}/>,
    "circle-play": <CirclePlay size={size} style={{...style}}/>
  };

  return icon_map[name] || null;
}
