import {
  Instagram,
  Store,
  NotebookText,
  SquarePlus,
  Shirt,
  TextCursorInput,
  TextCursor,
  PhoneIncoming,
  List,
  SlidersHorizontal,
  ListFilter,
  SquareCheck,
  Component,
  ToggleRight,
  Link2,
  Mail,
  KeyRound,
  CalendarRange,
  CalendarClock,
  CalendarFold,
  Calendar,
  CalendarSearch,
  Palette,
  MessageSquare,
  MessageSquareText,
  MessageCircleMore,
  Star,
  Smile,
  ArrowUpDown,
  ImageUp,
  Images,
  ClipboardPen,
  Rows2,
  Linkedin,
  Twitter,
  MessageCircle,
} from "lucide-react";

export default function DynamicIcon({ name, size }) {
  const icon_map = {
    instagram: <Instagram size={size} />,
    store: <Store size={size} />,
    "notebook-text": <NotebookText size={size} />,
    "square-plus": <SquarePlus size={size} />,
    shirt: <Shirt size={size} />,
    "text-cursor-input": <TextCursorInput size={size} />,
    "text-cursor": <TextCursor size={size} />,
    "phone-incoming": <PhoneIncoming size={size} />,
    list: <List size={size} />,
    "sliders-horizontal": <SlidersHorizontal size={size} />,
    "list-filter": <ListFilter size={size} />,
    "square-check": <SquareCheck size={size} />,
    component: <Component size={size} />,
    "toggle-right": <ToggleRight size={size} />,
    "link-2": <Link2 size={size} />,
    mail: <Mail size={size} />,
    "key-round": <KeyRound size={size} />,
    "calendar-range": <CalendarRange size={size} />,
    "calendar-clock": <CalendarClock size={size} />,
    "calendar-fold": <CalendarFold size={size} />,
    calendar: <Calendar size={size} />,
    "calendar-search": <CalendarSearch size={size} />,
    palette: <Palette size={size} />,
    "message-square": <MessageSquare size={size} />,
    "message-square-text": <MessageSquareText size={size} />,
    "message-circle-more": <MessageCircleMore size={size} />,
    star: <Star size={size} />,
    smile: <Smile size={size} />,
    "arrow-up-down": <ArrowUpDown size={size} />,
    "image-up": <ImageUp size={size} />,
    images: <Images size={size} />,
    "clipboard-pen": <ClipboardPen size={size} />,
    "rows-2": <Rows2 size={size} />,
    linkedin: <Linkedin size={size} />,
    twitter: <Twitter size={size} />,
    whatsapp: <MessageCircle size={size} />,
  };

  return icon_map[name] || null;
}
