let defaultStyle = {
    flexDirection: 'column',
    display:"flex",
    justifyContent: 'flex-start',
    alignItems: 'center',
    alignContent: 'center',
    flexWrap: 'nowrap',
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: 'auto',
    order: 0,
    alignSelf: 'auto',
    width: '100%',
    height: 'auto',
    color: '#000000',
    backgroundColor: '#ffffff',
    padding: '10px',
    margin: '10px',
    border: 'none',
    borderRadius: '20px',
    boxShadow: 'none',
    minHeight:"70px",
    minWidth:"70px"
  };


let fieldStyle = {
    flexDirection: 'column',
    display:"flex",
    justifyContent: 'flex-start',
    alignItems: 'center',
    alignContent: 'center',
    flexWrap: 'nowrap',
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: 'auto',
    order: 0,
    alignSelf: 'auto',
    width: '100%',
    height: 'auto',
    color: '#000000',
    backgroundColor: '#ffffff',
    padding: '10px',
    margin: '0px',
    border: '2px solid black',
    borderRadius: '20px',
    boxShadow: 'none',
};

let labelStyle = {
    flexDirection: 'column',
    display:"flex",
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    alignContent: 'flex-start',
    flexWrap: 'nowrap',
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: 'auto',
    order: 0,
    alignSelf: 'auto',
    width: '100%',
    height: 'auto',
    color: '#000000',
    padding: '0px',
    margin: '0px',
    border: 'none',
    borderRadius: '0',
    boxShadow: 'none',
};

export {defaultStyle, labelStyle , fieldStyle};